const categories = {
  ahorro: "Ahorro",
  comida: "Comida",
  casa: "Casa",
  gastos: "Gastos Varios",
  ocio: "Ocio",
  salud: "Salud",
  suscripciones: "Suscripciones",
  // educacion: "Educación",
  // transporte: "Transporte",
  // entretenimiento: "Entretenimiento",
  // ropa: "Ropa",
  // regalos: "Regalos",
  // mascotas: "Mascotas",
  // impuestos: "Impuestos",
  // viajes: "Viajes",
  // seguro: "Seguro",
  // inversiones: "Inversiones",
  // hobbies: "Hobbies",
  // belleza: "Belleza",
  // gimnasio: "Gimnasio",
  // electrodomesticos: "Electrodomésticos",
  // deudas: "Deudas",
  // automovil: "Automóvil",
  // libros: "Libros",
  // música: "Música",
  // tecnologia: "Tecnología",
  // deportes: "Deportes",
  // medicamentos: "Medicamentos",
  // hogar: "Hogar",
  // jardineria: "Jardinería",
  // reparaciones: "Reparaciones",
  // eventos: "Eventos",
  // caridad: "Caridad",
  // alimentos: "Alimentos",
  // bebidas: "Bebidas",
  // snacks: "Snacks",
  // herramientas: "Herramientas",
  // joyeria: "Joyería",
  // arte: "Arte",
  // artefactos: "Artefactos",
  // juegos: "Juegos",
}

export default categories
